version: 2
jobs:
  test_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.6-stretch
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main" | sudo tee -a /etc/apt/sources.list.d/jessie-backports.list
            sudo apt-get update
            sudo apt-get install -t jessie-backports -y openjdk-8-jre-headless
            sudo /usr/sbin/update-java-alternatives -s java-1.8.0-openjdk-amd64
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/regression_model/requirements.txt
            py.test -vv packages/regression_model/tests
  test_ml_api:
    working_directory: ~\project
    docker:
      - image: circleci/python:3.7.6-stretch
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main" | sudo tee -a /etc/apt/sources.list.d/jessie-backports.list
            sudo apt-get update
            sudo apt-get install -t jessie-backports -y openjdk-8-jre-headless
            sudo /usr/sbin/update-java-alternatives -s java-1.8.0-openjdk-amd64
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/ml_api/requirements.txt
            py.test -vv packages/ml_api/tests

  train_and_upload_regression_model:
    working_directory: ~\project
    docker:
      - image: circleci/python:3.7.6-stretch
    steps:
      - checkout
      - run:
          name: Setup enviornment
          command: |
            echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main" | sudo tee -a /etc/apt/sources.list.d/jessie-backports.list
            sudo apt-get update
            sudo apt-get install -t jessie-backports -y openjdk-8-jre-headless
            sudo /usr/sbin/update-java-alternatives -s java-1.8.0-openjdk-amd64
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/ml_api/requirements.txt
      - run:
          name: Publish model
          command: |
            . venv/bin/activate
            chmod +x ./scripts/publish_model.sh
            PYTHONPATH=./packages/regression_model python3 packages/regression_model/regression_model/master.py
            ./scripts/publish_model.sh ./packages/regression_model/

workflows:
  version: 2
  test-all:
    jobs:
      - test_regression_model
      - test_ml_api
      - train_and_upload_regression_model
      - test_ml_api:
          requires:
            - train_and_upload_regression_model
